INSERT INTO VEHICULO(ID_VEHICULO , TIPO_VEHICULO, CILINDRAJE, PLACA)VALUES(100, 'Moto', 150, 'AAA000');

INSERT INTO TIQUETE(ID_TIQUETE, ESTADO, REGISTRO_INGRESO, REGISTRO_SALIDA, VALOR_SERVICIO, ID_VEHICULO) VALUES (100, TRUE, '2019-07-23', NULL, NULL,100);



